### ISSUE TITLE
Open to using Workspace dependencies and updating to ndarray "^0.16"?

### ISSUE THREAD

**Issue by skewballfox** [wavey-ai/mel-spec#15]
This is more to see if you want me to open a PR for this. I needed to update to ndarray "0.16" to make this library compatible with burn-ndarray. I did, it builds and passes test. Currently you are defining the dependency versions per project, but this can be managed in the toplevel cargo.toml for the workspace. It would make it easier to version bumps in the future.

**Comment by jbrough** [comment]
yes, please do. 

I'll merge in and bump the minor version.

I may then take the opportunity to remove the workspaces entirely and increment the major version. no reason this shouldn't just be "mel-spec". 

Ive moved the audio helpers to https://github.com/wavey-ai/soundkit and the pipeline isn't that useful at all since https://github.com/wavey-ai/mel-spec/issues/12  - I think I just need to update the examples before doing that.

I used whisper-burn in the related hush project and mel-spec should be able to support the burn variants of ndarray so would be great to add your changes.
